#!/bin/sh

NAME=atca-ioc-w7x-intrlck-driver
PACKAGE_NAME=$NAME-dkms

DEBVERS=$(dpkg-query -W -f='${Version}' $PACKAGE_NAME | awk -F- '{print $1}')
VERSION=$(echo "$DEBVERS" | sed -e 's/[+-].*//' -e 's/~//g')

set -e

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $NAME -v $VERSION --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
