######################################################################
##
## Filename: chop_gen_wave.fdo
## Created on: Mon Mar 27 11:55:55 GMT Daylight Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation windows.
##
######################################################################
add wave *
add wave /glbl/GSR
