######################################################################
##
## Filename: testbench.fdo
## Created on: Fri Mar 06 18:15:24 GMT Standard Time 2015
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#
# Create work library
#
vlib work
#
# Compile sources
#
vcom -explicit  -93 "../design/dsp48_test1.vhd"
vcom -explicit  -93 "./dsp48_test1_tb.vhd"
#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps  -lib work work.testbench
#
# Source the wave do file
#
do {dsp48_test1_tb_wave.do}
#
# Set the window types
#
view wave
view structure
view signals
#
# Source the user do file
#
#do {dsp48_test1_tb.udo}
#
# Run simulation for this time
#
run 200ns
#
# End
#
