######################################################################
##
## Filename: RT_packet_gen_tb.fdo
## Created on: Wed Mar 25 11:17:58 GMT Standard Time 2015
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#
# Create work library
#
vlib work
#
# Compile sources
#
vlog  "../../ip_cores/FpMult32.v"
vlog  "../../ip_cores/FP48.v"
vlog  "../../ip_cores/FpAdd32.v"
vlog  "../../ip_cores/RT_FIFO.v"
vlog  "../design/PCIe_packet_gen.v" +incdir+../design
vlog  "RT_packet_gen_tb.v"
vlog  "E:/Xilinx/14.7/ISE_DS/ISE/verilog/src/glbl.v"
#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps  -L xilinxcorelib_ver -L unisims_ver -L unimacro_ver -L secureip -lib work work.RT_packet_gen_tb glbl
#
# Source the wave do file
#
do {RT_packet_gen_tb_wave.do}
#
# Set the window types
#
view wave
view structure
view signals
#
# Source the user do file
#
#do {RT_packet_gen_tb.udo}
#
# Run simulation for this time
#
run 50 us
#
# End
#
